from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("I LOVEE YOUUU 💕")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG KAMU 💝💖💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SELAMANYA 💕")
        await e.edit("💘💘💘💘")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("I LOVE YOUUUU")
        await e.edit("MY BABY")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("SAYANG KAMU💞")


@register(outgoing=True, pattern='^.dino(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`DIN DINNN.....`")
    sleep(1)
    await typew.edit("`DINOOOOSAURUSSSSS!!`")
    sleep(1)
    await typew.edit("`🏃                        🦖`")
    await typew.edit("`🏃                       🦖`")
    await typew.edit("`🏃                      🦖`")
    await typew.edit("`🏃                     🦖`")
    await typew.edit("`🏃   `LARII`          🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃WOARGH!   🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                    🦖`")
    await typew.edit("`🏃                     🦖`")
    await typew.edit("`🏃 hadoh kesel aku    🦖`")
    await typew.edit("`🏃                   🦖`")
    await typew.edit("`🏃                  🦖`")
    await typew.edit("`🏃                 🦖`")
    await typew.edit("`🏃                🦖`")
    await typew.edit("`🏃               🦖`")
    await typew.edit("`🏃              🦖`")
    await typew.edit("`🏃             🦖`")
    await typew.edit("`🏃            🦖`")
    await typew.edit("`🏃           🦖`")
    await typew.edit("`🏃          🦖`")
    await typew.edit("`🏃         🦖`")
    await typew.edit("`ANJIR DIAAKIN DEKET!!!`")
    sleep(1)
    await typew.edit("`🏃       🦖`")
    await typew.edit("`🏃      🦖`")
    await typew.edit("`🏃     🦖`")
    await typew.edit("`🏃    🦖`")
    await typew.edit("`eh bentar dia kan udh punah`")
    sleep(1)
    await typew.edit("`TERNYATA GUA YAHG HALU`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`KALO LU GABUT BIASANYA NGAPAIN`")
        await e.edit("`KALO GUA GABUT BIASANYA CEWE GUA GW PUTUSIN`")
        await e.edit("`BERHUBUNG GA ADA CEWE ENAKNYA NGAPAIN YA`")
        await e.edit("`MAU TIDUR`")
        await e.edit("`TAPIIIII`")
        await e.edit("`TAKUT`")
        await e.edit("`TAKUT KALO NGOROK JADI LAGU`")
        await e.edit("`EMMMM GA JADI TIDUR AH`")
        await e.edit("`HOOAAAAAAAH`")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("`Taraaaaa`")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🐌                       🚶")
        await e.edit("🐌                      🚶")
        await e.edit("🐌                     🚶")
        await e.edit("🐌                    🚶")
        await e.edit("🐌                   🚶")
        await e.edit("🐌                  🚶")
        await e.edit("🐌                 🚶")
        await e.edit("🐌                🚶")
        await e.edit("🐌               🚶")
        await e.edit("🐌              🚶")
        await e.edit("🐌             🚶")
        await e.edit("🐌            🚶")
        await e.edit("🐌           🚶")
        await e.edit("🐌          🚶")
        await e.edit("🐌         🚶")
        await e.edit("🐌        🚶")
        await e.edit("🐌       🚶")
        await e.edit("🐌      🚶")
        await e.edit("🐌     🚶")
        await e.edit("🐌    🚶")
        await e.edit("🐌   🚶")
        await e.edit("🐌  🚶")
        await e.edit("🐌 🚶")
        await e.edit("🐌🚶")
        await e.edit("🚶🐌")
        await e.edit("🚶 🐌")
        await e.edit("🚶  🐌")
        await e.edit("🚶   🐌")
        await e.edit("🚶    🐌")
        await e.edit("🚶     🐌")
        await e.edit("🚶      🐌")
        await e.edit("🚶       🐌")
        await e.edit("🚶        🐌")
        await e.edit("🚶         🐌")
        await e.edit("🚶          🐌")
        await e.edit("🚶           🐌")
        await e.edit("🚶            🐌")
        await e.edit("🚶             🐌")
        await e.edit("🚶              🐌")
        await e.edit("🚶               🐌")
        await e.edit("🚶                🐌")
        await e.edit("🚶                 🐌")
        await e.edit("🚶                  🐌")
        await e.edit("🚶                   🐌")
        await e.edit("🚶                    🐌")
        await e.edit("🚶                     🐌")
        await e.edit("🚶                      🐌")
        await e.edit("🚶                       🐌")
        await e.edit("🚶                        🐌")
        await e.edit("🚶                         🐌")
        await e.edit("🚶                          🐌")
        await e.edit("🚶                           🐌")
        await e.edit("🚶                            🐌")
        await e.edit("🚶                             🐌")
        await e.edit("🚶                              🐌")
        await e.edit("🚶                               🐌")
        await e.edit("🚶                                🐌")
        await e.edit("🚶                                 🐌")
        await e.edit("`GUA LAGI LEMAH`")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("🙈")
        await e.edit("🙉")
        await e.edit("😂")
        await e.edit("🐌                       🚶")
        await e.edit("🐌                      🚶")
        await e.edit("🐌                     🚶")
        await e.edit("🐌                    🚶")
        await e.edit("🐌                   🚶")
        await e.edit("🐌                  🚶")
        await e.edit("🐌                 🚶")
        await e.edit("🐌                🚶")
        await e.edit("🐌               🚶")
        await e.edit("🐌              🚶")
        await e.edit("🐌             🚶")
        await e.edit("🐌            🚶")
        await e.edit("🐌           🚶")
        await e.edit("🐌          🚶")
        await e.edit("🐌         🚶")
        await e.edit("🐌        🚶")
        await e.edit("🐌       🚶")
        await e.edit("🐌      🚶")
        await e.edit("🐌     🚶")
        await e.edit("🐌    🚶")
        await e.edit("🐌   🚶")
        await e.edit("🐌  🚶")
        await e.edit("🐌 🚶")
        await e.edit("🐌🚶")
        await e.edit("🚶🐌")
        await e.edit("🚶 🐌")
        await e.edit("🚶  🐌")
        await e.edit("🚶   🐌")
        await e.edit("🚶    🐌")
        await e.edit("🚶     🐌")
        await e.edit("🚶      🐌")
        await e.edit("🚶       🐌")
        await e.edit("🚶        🐌")
        await e.edit("🚶         🐌")
        await e.edit("🚶          🐌")
        await e.edit("🚶           🐌")
        await e.edit("🚶            🐌")
        await e.edit("🚶             🐌")
        await e.edit("🚶              🐌")
        await e.edit("🚶               🐌")
        await e.edit("🚶                🐌")
        await e.edit("🚶                 🐌")
        await e.edit("🚶                  🐌")
        await e.edit("🚶                   🐌")
        await e.edit("🚶                    🐌")
        await e.edit("🚶                     🐌")
        await e.edit("🚶                      🐌")
        await e.edit("🚶                       🐌")
        await e.edit("🚶                        🐌")
        await e.edit("🚶                         🐌")
        await e.edit("🚶                          🐌")
        await e.edit("🚶                           🐌")
        await e.edit("🚶                            🐌")
        await e.edit("🚶                             🐌")
        await e.edit("🚶                              🐌")
        await e.edit("🚶                               🐌")
        await e.edit("🚶                                🐌")
        await e.edit("🐌                       🚶")
        await e.edit("🐌                      🚶")
        await e.edit("🐌                     🚶")
        await e.edit("🐌                    🚶")
        await e.edit("🐌                   🚶")
        await e.edit("🐌                  🚶")
        await e.edit("🐌                 🚶")
        await e.edit("🐌                🚶")
        await e.edit("🐌               🚶")
        await e.edit("🐌              🚶")
        await e.edit("🐌             🚶")
        await e.edit("🐌            🚶")
        await e.edit("🐌           🚶")
        await e.edit("🐌          🚶")
        await e.edit("🐌         🚶")
        await e.edit("🐌        🚶")
        await e.edit("🐌       🚶")
        await e.edit("🐌      🚶")
        await e.edit("🐌     🚶")
        await e.edit("🐌    🚶")
        await e.edit("🐌   🚶")
        await e.edit("🐌  🚶")
        await e.edit("🐌 🚶")
        await e.edit("🐌🚶")
        await e.edit("🚶🐌")
        await e.edit("🚶 🐌")
        await e.edit("🚶  🐌")
        await e.edit("🚶   🐌")
        await e.edit("🚶    🐌")
        await e.edit("🚶     🐌")
        await e.edit("🚶      🐌")
        await e.edit("🚶       🐌")
        await e.edit("🚶        🐌")
        await e.edit("🚶         🐌")
        await e.edit("🚶          🐌")
        await e.edit("🚶           🐌")
        await e.edit("🚶            🐌")
        await e.edit("🚶             🐌")
        await e.edit("🚶              🐌")
        await e.edit("🚶               🐌")
        await e.edit("🚶                🐌")
        await e.edit("🚶                 🐌")
        await e.edit("🚶                  🐌")
        await e.edit("🚶                   🐌")
        await e.edit("🚶                    🐌")
        await e.edit("🚶                     🐌")
        await e.edit("🚶                      🐌")
        await e.edit("🚶                       🐌")
        await e.edit("🚶                        🐌")
        await e.edit("🚶                         🐌")
        await e.edit("🚶                          🐌")
        await e.edit("🚶                           🐌")
        await e.edit("🚶                            🐌")
        await e.edit("🚶                             🐌")
        await e.edit("🚶                              🐌")
        await e.edit("🚶                               🐌")
        await e.edit("🚶                                🐌")
        await e.edit("🐌                       🚶")
        await e.edit("🐌                      🚶")
        await e.edit("🐌                     🚶")
        await e.edit("🐌                    🚶")
        await e.edit("🐌                   🚶")
        await e.edit("🐌                  🚶")
        await e.edit("🐌                 🚶")
        await e.edit("🐌                🚶")
        await e.edit("🐌               🚶")
        await e.edit("🐌              🚶")
        await e.edit("🐌             🚶")
        await e.edit("🐌            🚶")
        await e.edit("🐌           🚶")
        await e.edit("🐌          🚶")
        await e.edit("🐌         🚶")
        await e.edit("🐌        🚶")
        await e.edit("🐌       🚶")
        await e.edit("🐌      🚶")
        await e.edit("🐌     🚶")
        await e.edit("🐌    🚶")
        await e.edit("🐌   🚶")
        await e.edit("🐌  🚶")
        await e.edit("🐌 🚶")
        await e.edit("🐌🚶")
        await e.edit("🚶🐌")
        await e.edit("🚶 🐌")
        await e.edit("🚶  🐌")
        await e.edit("🚶   🐌")
        await e.edit("🚶    🐌")
        await e.edit("🚶     🐌")
        await e.edit("🚶      🐌")
        await e.edit("🚶       🐌")
        await e.edit("🚶        🐌")
        await e.edit("🚶         🐌")
        await e.edit("🚶          🐌")
        await e.edit("🚶           🐌")
        await e.edit("🚶            🐌")
        await e.edit("🚶             🐌")
        await e.edit("🚶              🐌")
        await e.edit("🚶               🐌")
        await e.edit("🚶                🐌")
        await e.edit("🚶                 🐌")
        await e.edit("🚶                  🐌")
        await e.edit("🚶                   🐌")
        await e.edit("🚶                    🐌")
        await e.edit("🚶                     🐌")
        await e.edit("🚶                      🐌")
        await e.edit("🚶                       🐌")
        await e.edit("🚶                        🐌")
        await e.edit("🚶                         🐌")
        await e.edit("🚶                          🐌")
        await e.edit("🚶                           🐌")
        await e.edit("🚶                            🐌")
        await e.edit("🚶                             🐌")
        await e.edit("🚶                              🐌")
        await e.edit("🚶                               🐌")
        await e.edit("🚶                                🐌")
        await e.edit("`HDEEH LEMEESSS`")


@register(outgoing=True, pattern='^.terkadang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`uy uhtea`")
    sleep(1)
    await typew.edit("`I LOVE YOU 3500`")
    sleep(1)
    await typew.edit("`💝💝💝💝💝💝💝`")
    sleep(1)
    await typew.edit("`tapi gua minta kembalian 500`")
    sleep(1)
    await typew.edit("`biar jadi lopyu 3000`")
    sleep(1)
    await typew.edit("`kwkwkkwk😉`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.mf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`mf g dl` **ミ(ノ;_ _)ノ=3** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`menghubungkan ke hati target`",
            "`berhasil terhubung ke hati target`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n█████████CINTAKU███████████ `",
            f"`Cintaku Sekarang Sepenuhnya Terkirim ke kamu, Dan Sekarang Aku Sangat Mencintai Mu, I Love You 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai, I LOVE YOU 💞`")
    sleep(1)
    await typew.edit("`I LOVE YOU SO MUCH!`")
    sleep(1)
    await typew.edit("`I NEED YOU!`")
    sleep(1)
    await typew.edit("`I WANT TO BE YOUR BOYFRIEND!`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💕💗`")
    sleep(1)
    await typew.edit("`AKU TRESNO KOE💗💞`")
    sleep(1)
    await typew.edit("`AKU SAYANG KAMU💝💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💟💖`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💘💓`")
    sleep(1)
    await typew.edit("`Tapi Bo'ong`")
# Create by myself @localheart

CMD_HELP.update({
    "gabut":
    "⚡𝘾𝙈𝘿⚡`.gabut` ;⚡𝘾𝙈𝘿⚡ `.dino`\
    \nPenjelasan: ntahlah gabut doang.\
    \n\n⚡𝘾𝙈𝘿⚡`.gombal`\
    \nPenjelasan: buat bercanda\
    \n\n⚡𝘾𝙈𝘿⚡`.cinta`\
    \nPenjelasan: mengirim cintamu ke seseorang.\
    \n\n⚡𝘾𝙈𝘿⚡`.sayang`\
    \nPenjelasan: untuk jadi buaya.\
    \n\n⚡𝘾𝙈𝘿⚡`.terkadang`\
    \nPenjelasan: Auk dah iseng doang."
})
